# Generated by Django 5.0.6 on 2024-07-24 20:57

import advertisement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('BodyType', models.CharField(choices=[('cabriolet', 'cabriolet'), ('coupe', 'coupe'), ('hatchback-5-Door', 'hatchback 5 door'), ('Hatchback-3-Door', 'hatchback 3 door'), ('sedan', 'sedan'), ('stationwagon', 'stationwagon'), ('suv', 'suv')], default='cabriolet', max_length=150)),
                ('Mileage', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('FuelType', models.CharField(choices=[('Petrol', 'petrol'), ('Diesel', 'diesel'), ('Electric', 'electric'), ('Hybrid', 'hybrid')], default='Petrol', max_length=150)),
                ('TransmissionType', models.CharField(choices=[('Manual', 'manual'), ('Automatic', 'automatic'), ('Semi-Automatic', 'semi-automatic')], default='Manual', max_length=150)),
                ('Status', models.CharField(choices=[('Unused', 'unused'), ('Used', 'used')], default='Unused', max_length=150)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('Visit_count', models.IntegerField(default=0)),
                ('Is_show', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_cat', to='advertisement.category')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=advertisement.models.image_upload_to_car)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='advertisement.car')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_conversation', to='advertisement.car')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starter_conv', to=settings.AUTH_USER_MODEL)),
                ('mesages', models.ManyToManyField(to='advertisement.message')),
            ],
        ),
        migrations.CreateModel(
            name='OthersAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Propertytype', models.CharField(choices=[('Digital Goods', 'digital goods'), ('Kitchen', 'kitchen'), ('Intertainment', 'intertainment'), ('Personal Items', 'personal items')], default='Digital Goods', max_length=150)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('Status', models.CharField(choices=[('Unused', 'unused'), ('Used', 'used')], default='Unused', max_length=150)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('Visit_count', models.IntegerField(default=0)),
                ('Is_show', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherad_cat', to='advertisement.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otherad_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=advertisement.models.image_upload_to_other)),
                ('other', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_image', to='advertisement.othersads')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Propertytype', models.CharField(choices=[('Apartment', 'apartment'), ('House', 'house'), ('Villa', 'villa'), ('Studio', 'studio'), ('Penthouse', 'penthouse'), ('Residence', 'residence'), ('Under Construction Building', 'under construction building'), ('Land', 'land'), ('Commercial Property', 'commercial property'), ('Warehouse', 'warehouse')], default='Apartment', max_length=150)),
                ('TitleDeedType', models.CharField(choices=[('Turkish Title Deed', 'turkish title deed'), ('Equivalent Title Deed', 'equivalent title deed'), ('Foreign Title Deed', 'foreign title deed'), ('State Social Housing', 'state social housing'), ('Martyr Child ', 'martyr child'), ('Allocation', 'allocation'), ('Veteran Points', 'veteran points'), ('Leasehold', 'leasehold')], default='Turkish Title Deed', max_length=150)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('Size', models.DecimalField(decimal_places=2, default=0, max_digits=150)),
                ('NumberOfBedrooms', models.CharField(choices=[('Studio', 'studio'), ('1 Bedroom', '1 bedroom'), ('2 Bedrooms', '2 bedrooms'), ('3 Bedrooms', '3 bedrooms'), ('4 Bedrooms', '4 bedrooms'), ('5+ Bedrooms', '5+ bedrooms')], default='1 Bedroom', max_length=150)),
                ('FurnishingStatus', models.CharField(choices=[('Unfurnished', 'unfurnished'), ('Partially Furnished', 'partially furnished'), ('Furnished', 'furnished'), ('Only White Goods', 'only white goods')], default='Unfurnished', max_length=150)),
                ('Status', models.CharField(choices=[('Unused', 'unused'), ('Used', 'used')], default='Unused', max_length=150)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('Visit_count', models.IntegerField(default=0)),
                ('Is_show', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_cat', to='advertisement.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=advertisement.models.image_upload_to_real_estate)),
                ('real_estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_image', to='advertisement.realestate')),
            ],
        ),
    ]
