# Generated by Django 5.0.6 on 2024-07-24 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='carconversation',
            old_name='mesages',
            new_name='messages',
        ),
        migrations.AlterField(
            model_name='carconversation',
            name='starter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_starter_conv', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OtherConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='advertisement.message')),
                ('other_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_conversation', to='advertisement.othersads')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_starter_conv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.ManyToManyField(to='advertisement.message')),
                ('realestate_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_conversation', to='advertisement.realestate')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realestate_starter_conv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
