# Generated by Django 5.0.6 on 2024-07-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_rename_mesages_carconversation_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='BodyType',
            field=models.CharField(choices=[('cabriolet', 'cabriolet'), ('coupe', 'coupe'), ('hatchback5door', 'hatchback 5 door'), ('hatchback3door', 'hatchback 3 door'), ('sedan', 'sedan'), ('stationwagon', 'stationwagon'), ('suv', 'suv')], default='cabriolet', max_length=150),
        ),
        migrations.AlterField(
            model_name='othersads',
            name='Propertytype',
            field=models.CharField(choices=[('digitalgoods', 'digital goods'), ('kitchen', 'kitchen'), ('intertainment', 'intertainment'), ('personalitems', 'personal items')], default='digitalgoods', max_length=150),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='Propertytype',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('villa', 'villa'), ('studio', 'studio'), ('penthouse', 'penthouse'), ('residence', 'residence'), ('underconstructionbuilding', 'under construction building'), ('land', 'land'), ('commercialproperty', 'commercial property'), ('warehouse', 'warehouse')], default='apartment', max_length=150),
        ),
    ]
