# Generated by Django 5.0.6 on 2024-07-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_car_is_published_othersads_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('car_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_ad_message', to='advertisement.car')),
            ],
        ),
    ]
