# Generated by Django 5.0.6 on 2024-07-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_messagetoad'),
    ]

    operations = [
        migrations.AddField(
            model_name='othersads',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
