# Generated by Django 5.0.6 on 2024-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_othersads_admin_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='realestate',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
