# Generated by Django 5.0.6 on 2024-07-21 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_car_admin_message_realestate_admin_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageToAd',
        ),
    ]
