# Generated by Django 5.0.6 on 2024-06-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_yourmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
