# Generated by Django 5.0.6 on 2024-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
